baseURL     = 'https://minimumcd.org/'
description = 'Minimum CD defines a minimum set of problems to solve to help teams achieve the benefits of continuous delivery. By implementing these essential practices, an organization can improve both the quality of the work environment and the outcomes of software development.'
title       = 'Minimum Viable Continuous Delivery'

enableGitInfo   = true
enableRobotsTXT = true

disableKinds = [
  "taxonomy",
  "term"
]

# You can add your own taxonomies
[taxonomies]
  category = "categories"
  tag      = "tags"

# Configure how URLs look like per section.
[permalinks]
  blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration.
[imaging]
  anchor         = "Smart"
  quality        = 75
  resampleFilter = "CatmullRom"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser.attribute]
      block = true
[markup.goldmark.renderer]
  unsafe = true
[markup.highlight]
  # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
  style = "tango"
  # Uncomment if you want your chosen highlight style used for code blocks without a specified language
  # guessSyntax = "true"

  # Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
  section = [
    "HTML",
    "RSS",
    "print"
  ]

[params]
  preview_image = '/images/minimumCD-Tagline.png'

  # gcs_engine_id = "c68e6136e96d14a0f"
  github_branch       = "master"
  github_project_repo = "https://github.com/Minimum-CD/cd-manifesto"
  github_repo         = "https://github.com/Minimum-CD/cd-manifesto"

  # Google Custom Search Engine ID. Remove or comment out to disable search.
  # gcs_engine_id = "d72aa9b2712488cc3"

  # Enable Lunr.js offline search
  offlineSearch = true

  prism_syntax_highlighting = true
  pygmentsCodeFences        = true
  pygmentsStyle             = "tango"
  pygmentsUseClasses        = false
  pygmentsUseClassic        = false

  custom_js = [
    "https://buttons.github.io/buttons.js"
  ]

  [params.taxonomy]
    # set taxonomyCloud = [] to hide taxonomy clouds
    taxonomyCloud = [
      "categories",
      "tags"
    ]

    # If used, must have same length as taxonomyCloud
    taxonomyCloudTitle = [
      "Categories",
      "Tag Cloud"
    ]

    # set taxonomyPageHeader = [] to hide taxonomies on the page headers
    taxonomyPageHeader = [
      "categories",
      "tags"
    ]

  [params.copyright]
    authors   = "MinimumCD Authors | [CC BY 4.0](https://creativecommons.org/licenses/by/4.0) | "
    from_year = 2020

  [params.ui]
    breadcrumb_disable                    = false
    navbar_logo                           = '/icons/logo.svg'
    navbar_translucent_over_cover_disable = false
    show_nav_title                        = true
    sidebar_cache_limit                   = 10
    sidebar_menu_compact                  = true
    sidebar_menu_foldable                 = true
    sidebar_search_disable                = true

  [params.links]
    [[params.links.developer]]
      desc = "Contribute!"
      icon = "fab fa-github"
      name = "GitHub"
      url  = "https://github.com/Minimum-CD/cd-manifesto"

    [params.ui.feedback]
      enable = false

    [params.ui.readingtime]
      enable = false

[services]
  [services.googleAnalytics]
    id = "G-KVLFMQXEF1"

[module]
  proxy = "direct"
  [[module.imports]]
    path = "github.com/google/docsy"
